/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module testSM_2 (
    input clk,
    input rst,
    input [7:0] result,
    output reg [5:0] alufn,
    output reg [7:0] a,
    output reg [7:0] b,
    input pause,
    output reg error
  );
  
  
  
  reg [26:0] M_counter_d, M_counter_q = 1'h0;
  localparam ADD_state = 5'd0;
  localparam ADDV_state = 5'd1;
  localparam ADDZ_state = 5'd2;
  localparam SUB_state = 5'd3;
  localparam SUBZ_state = 5'd4;
  localparam CMPEQT_state = 5'd5;
  localparam CMPEQF_state = 5'd6;
  localparam CMPLTT_state = 5'd7;
  localparam CMPLTF_state = 5'd8;
  localparam CMPLET_state = 5'd9;
  localparam CMPLEF_state = 5'd10;
  localparam AND_state = 5'd11;
  localparam OR_state = 5'd12;
  localparam XOR_state = 5'd13;
  localparam A_state = 5'd14;
  localparam SHL_state = 5'd15;
  localparam SHR_state = 5'd16;
  localparam SRA_state = 5'd17;
  localparam ERROR_state = 5'd18;
  
  reg [4:0] M_state_d, M_state_q = ADD_state;
  
  always @* begin
    M_state_d = M_state_q;
    M_counter_d = M_counter_q;
    
    alufn = 6'h00;
    a = 8'h00;
    b = 8'h00;
    error = 1'h0;
    if (!pause) begin
      M_counter_d = M_counter_q + 1'h1;
    end
    
    case (M_state_q)
      ADD_state: begin
        alufn = 6'h00;
        a = 8'h1e;
        b = 8'h37;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'h55) begin
            M_state_d = ADDV_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      ADDV_state: begin
        alufn = 6'h00;
        a = 8'hf1;
        b = 8'hee;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'hdf) begin
            M_state_d = ADDZ_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      ADDZ_state: begin
        alufn = 6'h00;
        a = 8'h00;
        b = 8'h00;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'h00) begin
            M_state_d = SUB_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      SUB_state: begin
        alufn = 6'h01;
        a = 8'h55;
        b = 8'h1e;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'h37) begin
            M_state_d = SUBZ_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      SUBZ_state: begin
        alufn = 6'h01;
        a = 8'h00;
        b = 8'h00;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'h00) begin
            M_state_d = CMPEQT_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      CMPEQT_state: begin
        alufn = 6'h33;
        a = 8'he0;
        b = 8'he0;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'h01) begin
            M_state_d = CMPEQF_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      CMPEQF_state: begin
        alufn = 6'h33;
        a = 8'hfe;
        b = 8'he1;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'h00) begin
            M_state_d = CMPLTT_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      CMPLTT_state: begin
        alufn = 6'h35;
        a = 8'h1e;
        b = 8'h55;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'h01) begin
            M_state_d = CMPLTF_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      CMPLTF_state: begin
        alufn = 6'h35;
        a = 8'hde;
        b = 8'had;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'h00) begin
            M_state_d = CMPLET_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      CMPLET_state: begin
        alufn = 6'h37;
        a = 8'hc0;
        b = 8'hc0;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'h01) begin
            M_state_d = CMPLEF_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      CMPLEF_state: begin
        alufn = 6'h37;
        a = 8'hfe;
        b = 8'hed;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'h00) begin
            M_state_d = AND_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      AND_state: begin
        alufn = 6'h18;
        a = 8'h96;
        b = 8'h35;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'h14) begin
            M_state_d = OR_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      OR_state: begin
        alufn = 6'h1e;
        a = 8'hb2;
        b = 8'h34;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'hb6) begin
            M_state_d = XOR_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      XOR_state: begin
        alufn = 6'h16;
        a = 8'hd6;
        b = 8'h65;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'hb3) begin
            M_state_d = A_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      A_state: begin
        alufn = 6'h1a;
        a = 8'h66;
        b = 8'hdc;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'h66) begin
            M_state_d = SHL_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      SHL_state: begin
        alufn = 6'h20;
        a = 8'h1e;
        b = 8'hff;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'h00) begin
            M_state_d = SHR_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      SHR_state: begin
        alufn = 6'h21;
        a = 8'hfa;
        b = 8'h11;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'h7d) begin
            M_state_d = SRA_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      SRA_state: begin
        alufn = 6'h23;
        a = 8'hf0;
        b = 8'h0d;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (result == 8'hff) begin
            M_state_d = ADD_state;
            M_counter_d = 27'h0000000;
          end else begin
            M_state_d = ERROR_state;
          end
        end
      end
      ERROR_state: begin
        error = 1'h1;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
      M_state_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
      M_state_q <= M_state_d;
    end
  end
  
endmodule
